# DataSource Config
spring:
  datasource:
    username: root
    password: 12345678
    url: jdbc:mysql:///demo?userUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
